version: '3.3'
services:
  application:
    build: .
    command: sh -c "yarn start:dev"
    working_dir: /application
    depends_on:
      - db
    volumes:
      - .:/application
    ports:
      - 3000:3000
    networks:
      - test-development

  db:
    container_name: test-db
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - test-development

networks:
  test-development:

volumes:
  postgres:
    name: test_postgres
